apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: source-git
spec:
  type: git
  params:
    - name: url
      value: https://github.com/jensdriller/tekton-apiserver-build-and-push
    - name: revision
      value: master