---
apiVersion: v1
kind: Service
metadata:
  name: apiserver
spec:
  type: ClusterIP
  selector:  
    app: apiserver
  ports:
    - name: "http"
      port: 80
      targetPort: 8080
      # nodePort: 30080
